---
title: "A3"
output: html_document
---


```{r}
liquor_data <- readRDS("Capstone/Data/Analysis/LiquorLicenceData.rds")

glimpse(liquor_data)

unique_liquor_data <- sapply(liquor_data, n_distinct)

# what type of licences are there?
liquor_data %>%
  count(Category) %>%
  arrange(desc(n))

#see Notes_on_Data_Selection.md re the following exclusions
liquor_data <- liquor_data %>%
  filter(Category != "Pre-retail Licence",
         Category != "Wine and Beer Producer's Licence")

```



There appears to be duplicates in the data - at least at the address level. The same venue can have multiple licenses. Need to remove these for our summarised data purposes later (otherwise double counting will occur for number of liquor licenses within suburbs).
```{r}
liquor_data_deduped <- liquor_data %>%
  arrange(Licensee, TradingAs, Address, Suburb) %>%
  distinct(Licensee,  Address, Suburb, .keep_all = TRUE)

print(colSums(is.na(liquor_data_deduped)))


liquor_data_deduped %>%
  mutate(Longitude = as.numeric(Longitude),
         Latitude = as.numeric(Latitude)) %>%
  filter(Latitude != 0) %>%
  ggplot(aes(x=Longitude, y=Latitude)) +
  geom_point(alpha = 0.5, shape = 21, size = 1, fill = "steelblue") +
  theme_bw() +
  ggtitle("Where are the liquor licences in Victoria?")


```


```{r}
# create a df of the number of liquor licences per suburb
liquor_by_suburb <- liquor_data_deduped %>%
  filter(!is.na(Postcode)) %>%
  group_by(Postcode, Metro_Regional) %>%
  summarise(liq_lic_count = n(),
            gaming_count = sum(Gaming == "Y")) %>% ungroup() %>% mutate(Postcode = as.numeric(Postcode))


ggplot(data = liquor_by_suburb, aes(x = liq_lic_count, fill = Metro_Regional)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("steelblue", "orange"))


ggplot(data = filter(liquor_by_suburb, Postcode != 3000), aes(x = liq_lic_count, fill = Metro_Regional)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("steelblue", "orange"))


ggplot(data = filter(liquor_by_suburb, Postcode != 3000), aes(x = Metro_Regional, y = liq_lic_count, fill = Metro_Regional)) +
  geom_boxplot(alpha = 0.5) +
  scale_fill_manual(values = c("slategray", "orange")) +
  coord_flip() +
  theme_bw()

```


```{r}
##########################################
#---------- Read in Crime data ----------#
##########################################

# read in crime data
crime_data <- readRDS("Capstone/Data/Analysis/CrimeStatistics.rds")

head(crime_data)

# count the crime data by crime type
crime_counts <- crime_data %>%
  group_by(OffenceDivision) %>%
  summarise(total_incidents = sum(IncidentsRecorded))

# count the crime data by crime type
crime_counts <- crime_data %>%
  group_by(OffenceSubdivision) %>%
  summarise(total_incidents = sum(IncidentsRecorded))


########################################################
#---------- Summarised crime and liquor data ----------#
########################################################

# count the total incidents by suburb
crime_suburb_counts <- crime_data %>%
  group_by(Postcode, OffenceDivision) %>%
  summarise(total_incidents = sum(IncidentsRecorded)) %>% ungroup()


# join the crime and liquor license counts
crime_and_liquor <- crime_suburb_counts %>%
  left_join(liquor_by_suburb, by = "Postcode")

print(colSums(is.na(crime_and_liquor)))

# it appears that these are missing because there are no venues in these suburbs. Will recode the NAs to 0
crime_and_liquor %>%
  group_by(Postcode) %>%
  filter(is.na(liq_lic_count))


crime_and_liquor$liq_lic_count[is.na(crime_and_liquor$liq_lic_count)] <- 0
crime_and_liquor$gaming_count[is.na(crime_and_liquor$gaming_count)] <- 0

```


```{r}
crime_and_liquor %>%
  group_by(Postcode) %>%
  summarise(liq_lic_count = sum(liq_lic_count), total_incidents = sum(total_incidents)) %>%
  ggplot(aes(x=liq_lic_count, y= total_incidents)) + 
  geom_point() +
  labs(title = "Number of liquor licences and criminal incidents", 
       subtitle = "Is there a relationship between crime and liquor licenses?",
       x = "Liquor Licenses", y = "Criminal Incidents")



# remove the outlier, which is Melbourne
crime_and_liquor %>%
  group_by(Postcode) %>%
  summarise(liq_lic_count = sum(liq_lic_count), total_incidents = sum(total_incidents)) %>%
  filter(Postcode != 3000) %>%
  ggplot(aes(x=liq_lic_count, y= total_incidents)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  labs(title = "Number of liquor licences and criminal incidents", 
       subtitle = "Is there a relationship between crime and liquor licenses?",
       x = "Liquor Licenses", y = "Criminal Incidents") 
```


```{r}
crime_and_liquor %>%
  group_by(Postcode) %>%
  summarise(gaming_count = sum(gaming_count), total_incidents = sum(total_incidents)) %>%
  ggplot(aes(x=gaming_count, y= total_incidents)) + 
  geom_point() +
  labs(title = "Number of liquor licences and criminal incidents", 
       subtitle = "Is there a relationship between gambling and liquor licenses?",
       x = "Gaming Licenses", y = "Criminal Incidents") +
  geom_smooth()

```

```{r}

test <- crime_and_liquor %>%
  spread(key = OffenceDivision, value = total_incidents)

test[is.na(test)] <- 0

print(colSums(is.na(test)))


test %>%
  select(-Postcode) %>%
  as.matrix() %>%
  cor(method = "spearman") %>%
  corrplot::corrplot(tl.srt = 45, type = "lower")

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```

